spring:
  application:
    name: anki
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  liquibase:
    change-log: liquibase-changeLog.xml
logging:
  level:
    root: INFO
    com.stemlaur.anki: DEBUG
    org.jooq: DEBUG
server:
  port: 8081