spring:
  application:
    name: anki
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    root: INFO
    com.stemlaur.anki: DEBUG
